### ISSUE TITLE
Reversing an animation doesn't work as expected

### ISSUE THREAD

**Issue by snorpey** [colinmeinke/wilderness#58]
hey @colinmeinke,

thank you for creating this library. i've been looking for something like it for quite some time, and i'm really glad i found it. i've been using using it in one of my projects and noticed a little issue:

it seems that reversing an animation doesn't work properly.  i created a jsfiddle that shows this issue here: https://jsfiddle.net/a1xwzsyn/

thanks again for creating the library, it really is super useful to me.

**Comment by dalisoft** [comment]
I think reverse syntax for reverse path bezier, not a tween. I not sure. But this app is very useful, easy, fast and better ever i see and main premium feature is FREE

**Comment by colinmeinke** [comment]
Thanks for the report @snorpey and I'm glad you're finding Wilderness useful.

I've taken a quick look and there does definitely seem to be some issues around playing an animation multiple times. Another one of which is that if `finish` isn't defined on the secondary `play` it inherits the primary `finish` callback and gets into an infinite loop of animations.

I'm planning on focussing on Wilderness later this month over the holidays, finishing the core features, fixing any bugs and getting some tests written.

**Comment by colinmeinke** [comment]
@dalisoft reverse should work as @snorpey expects, playing the animation in reverse 😃

**Comment by dalisoft** [comment]
@colinmeinke I not used this option, but using Wilderness.js and works fine and even better than i think. Thank you for amazing library

**Comment by colinmeinke** [comment]
@snorpey sorry this has taken so long to look into, I've only just got my head back in the game. This is actually working as expected (at least in the latest release). When you call play a second time on a shape it actually picks up where it left off rather than creating a brand new animation (this is so you can play/pause an animation). In this case when you play again after it's finished you need to redefine the number of iterations you wish the animation to have, as it has finished it's initial 1 iteration, so play will have no effect. Here's how to do it https://jsfiddle.net/a1xwzsyn/1/
